### ISSUE TITLE
No direct issue - hg Eng = USA?

### ISSUE THREAD

**Issue by therealprocyon** [PokeAcer/wiimmfi-cheatcodes#7]
Hi,

Could it be possible that ENG is USA? So that the Dutch game is the US one, even though, it's the PAL game? I have only the English/PAL version to test. So it's appreciated if someone can test this theory.

**Comment by PokeAcer549** [comment]
It could be possible considering how Nintendo works

**Comment by PokeAcer549** [comment]
The ID4s are usually similar - dump the ROM and try it.

**Comment by therealprocyon** [comment]
It's actually the same, at least when you try the codes. I think I might've made an erroneous commit a while ago, which set USA HG to E. It should be USA/EN-E.

**Comment by therealprocyon** [comment]
Also the current USA should be E (others)
